name: spdxlib_hooks
description: Hook for generating SPDX license.
version: 0.1.0+1
repository: https://github.com/alestiago/license_lens/tree/main/packages/spdxlib_gen/hooks
issue_tracker: https://github.com/alestiago/license_lens/issues
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^3.6.1
  http: ^1.4.0
  mason: ^0.1.0
  meta: ^1.17.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
