name: spdxlib_gen

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/spdxlib_gen.yaml
      - "packages/spdxlib_gen/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/spdxlib_gen.yaml
      - "packages/spdxlib_gen/**"
    branches:
      - main

jobs:
  hooks:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.8.0
      format_directories: "test"
      analyze_directories: "test"
      report_on: "test"
      check_ignore: true
      no_example: true
      run_skipped: false
      working_directory: "packages/spdxlib_gen/hooks"