name: spdx_license

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/spdx_license.yaml
      - "packages/spdx_license/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/spdx_license.yaml
      - "packages/spdx_license/**"
    branches:
      - main

jobs:
  hooks:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      dart_sdk: 3.8.0
      analyze_directories: "lib,test,example"
      format_directories: "lib,test,example"
      report_on: "lib,test"
      check_ignore: true
      no_example: true
      working_directory: "packages/spdx_license/"